// packages/demos/vue-todomvc/src/components/AddTodo.vue
<template>
  <div class="todos-wrapper">
    <form v-on:submit="app.actions.addTodo">
      <input
        placeholder="I need to..."
        v-bind:value="app.state.newTodoTitle"
        v-on:input="app.actions.changeNewTodoTitle"
      />
      <button v-bind:disabled="app.state.newTodoTitle == ''">add</button>
    </form>
  </div>
</template>
<script>
import { connect } from '../app'

export default connect({
  name: 'AddTodo',
})
</script>

// packages/demos/react-todomvc/src/components/AddTodo/index.jsx
import * as React from 'react'
import { connect } from '../../app'
import { Wrapper, Input, Button, Form } from './elements'

const AddTodo = ({ app }) => (
  <Wrapper>
    <Form onSubmit={app.actions.addTodo}>
      <Input
        placeholder="I need to..."
        value={app.state.newTodoTitle}
        onChange={app.actions.changeNewTodoTitle}
      />
      <Button disabled={!app.state.newTodoTitle}>add</Button>
    </Form>
  </Wrapper>
)

export default connect(AddTodo)
