// packages/demos/todomvc/src/components/AddTodo/index.tsx
import * as React from 'react'
import { connect, Connect } from '../../app'
import { Wrapper, Input, Button, Form } from './elements'

const AddTodo: React.SFC<Connect> = ({ app }) => (
  <Wrapper>
    {app.computed.test(5)}
    <Form onSubmit={app.actions.addTodo}>
      <Input
        placeholder="I need to..."
        value={app.state.newTodoTitle}
        onChange={app.actions.changeNewTodoTitle}
      />
      <Button disabled={!app.state.newTodoTitle}>add</Button>
    </Form>
  </Wrapper>
)

export default connect(AddTodo)

// packages/demos/vue-todomvc/src/components/AddTodo.vue
<template>
  <div class="todos-wrapper">
    <form v-on:submit="app.actions.addTodo">
      <input
        placeholder="I need to..."
        v-bind:value="app.state.newTodoTitle"
        v-on:input="app.actions.changeNewTodoTitle"
      />
      <button v-bind:disabled="app.state.newTodoTitle == ''">add</button>
    </form>
  </div>
</template>
<script>
import { connect } from '../app'

export default connect({
  name: 'AddTodo',
})
</script>
