// packages/demos/react-todomvc/src/components/Todos/index.jsx
import * as React from 'react'
import { connect } from '../../app'
import { List } from './elements'
import Todo from '../Todo'

const Todos = ({ app }) => (
  <List>
    {app.state.todos.map(
      (todo) =>
        console.log('todo ID', todo.id) || <Todo key={todo.id} todo={todo} />
    )}
  </List>
)

export default connect(Todos)

// packages/demos/vue-todomvc/src/components/Todos.vue
<template>
  <ul class="todos-list">
    <todo v-for="todo in app.state.todos" v-bind:key="todo.id" v-bind:todo="todo" />
  </ul>
</template>
<script>
import { connect } from '../app'
import Todo from './Todo.vue'

export default connect({
  name: 'Todos',
  components: {
    Todo,
  },
})
</script>
