// packages/demos/todomvc/src/components/Todos/index.tsx
import * as React from 'react'
import { connect, Connect } from '../../app'
import { List } from './elements'
import Todo from '../Todo'

const Todos: React.SFC<Connect> = ({ app }) => (
  <List>
    {app.state.todos.map((todo) => <Todo key={todo.id} todo={todo} />)}
  </List>
)

export default connect(Todos)

// packages/demos/vue-todomvc/src/components/Todos.vue
<template>
  <ul class="todos-list">
    <todo v-for="todo in app.state.todos" v-bind:key="todo.id" v-bind:todo="todo" />
  </ul>
</template>
<script>
import { connect } from '../app'
import Todo from './Todo.vue'

export default connect({
  name: 'Todos',
  components: {
    Todo,
  },
})
</script>
