// packages/demos/overmind-todomvc/src/components/Todo/index.tsx
import * as React from 'react'
import { connect, Connect } from '../../app'
import { Todo } from '../../app/state'
import { Item, Completed } from './elements'

type Props = {
  todo: Todo
} & Connect

const Todo: React.SFC<Props> = ({ todo, app }) => (
  <Item onClick={() => app.actions.toggleCompleted(todo)}>
    <Completed completed={todo.completed}>✔</Completed> {todo.title}
  </Item>
)

export default connect(Todo)

// packages/demos/vue-todomvc/src/components/Todo.vue
<template>
  <li class="todo" v-on:click="app.actions.toggleCompleted(todo)">
        <button class="todo-completed" v-bind:class="{'todo-completed-complete': todo.completed }">
          ✔
        </button>
        {{todo.title}}
      </li>
</template>
<script>
import { connect } from '../app'

export default connect({
  name: 'Todo',
  props: ['todo'],
})
</script>
